# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Hat',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
