# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='image',
            field=models.ImageField(upload_to='hat_pics'),
        ),
    ]
