# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_auto_20171218_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product_app.Category'),
        ),
        migrations.AlterField(
            model_name='hat',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='product_app.Supplier'),
        ),
    ]
