# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 22:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_auto_20171228_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SC', 'Shoppingcart'), ('SM', 'Submitted'), ('PD', 'Paid'), ('PS', 'Processing'), ('SD', 'Shipped'), ('DD', 'Delivered')], default='SC', max_length=2),
        ),
    ]
