# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_auto_20171228_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
