# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_auto_20171229_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
