# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_auto_20171229_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
