# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_auto_20171229_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='order',
        ),
    ]
