# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 11:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0005_auto_20171229_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='GST',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='Auckland', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{8,16}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, default='New Zealand', max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_line1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_line2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Zip Code'),
        ),
    ]
