name: Push To Demo

on:
  push:
    branches: [ env/ck-test, env/db-test, env/testing ]

 
jobs:
  Test:
    name: Setup and Test
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ '3.7' ]
        
    outputs:
      image_name: ${{ steps.output_step.outputs.IMAGE_NAME }}
      url: https://${{ steps.output_step.outputs.IMAGE_NAME }}.prowood.network/
    steps:
      - uses: actions/checkout@v2
      # - name: Extract branch name
        # shell: bash
        # run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
        # run: echo "IMAGE_NAME=$(git rev-parse --abbrev-ref HEAD)"| sed 's/\//_/g' >> $GITHUB_ENV
        # run: echo "IMAGE_NAME=$GITHUB_REF_NAME"| sed 's/env\//erp-/g' >> $GITHUB_ENV
      - id: output_step
        run: |
          echo "IMAGE_NAME=$GITHUB_REF_NAME"| sed 's/env\//erp-/g' >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          echo "https://$IMAGE_NAME.prowood.network/"$GITHUB_REF_NAME
      - name: Run Tests
        run: |
          echo "------------------- run test ---------------- $IMAGE_NAME"
          
  DeployCKTest:
    name: Deploy to ${{needs.Test.outputs.image_name}}
    if: github.event.ref == 'refs/heads/env/ck-test'
    needs: Test
    runs-on: ubuntu-latest
    environment:
      name: Testing
      url: ${{needs.Test.outputs.url}}
    steps:
      - name: Deploy
        run: |
          echo ${{needs.Test.outputs.image_name}} ${{needs.Test.outputs.url}}
          echo I am deploying! 
        
  DeployDBTest:
    name: Deploy to db-test
    if: github.ref == 'refs/heads/db-test'
    needs: [Test]
    runs-on: ubuntu-latest
    environment:
      name: Testing
      url: 'http://db-test.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying!
        
  DeployTesting:
    name: Deploy to testing
    if: github.ref == 'refs/heads/testing'
    needs: [Test]
    runs-on: ubuntu-latest
    environment:
      name: Testing
      url: 'http://testing.myapp.com'
    steps:
      - name: Deploy
        run: echo I am deploying! 

